### ISSUE TITLE
aiohttp 3.1 release

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2829]
We have about 20 new features according to `CHANGES` folder.
More than a month of development.
Let's make 3.1 release.
Release fast, release early!

I'd like to finish
- [x] Add web.static and web.RouteTableDef.static #2795
- [x] Use `app.add_routes()` in server docs everywhere #2830 
- [ ] Implement dynamic prefix for subapps #2756

Rewrite server docs to get rid of mentioning `app.router.add_get()` and family in Quickstart / Advanced Usage sections. Replacing them by `app.add_routes()`.

Unfortunately the list of pending issues is still big (@thehesiod I remember about client timeouts, sure) but I see no reason to postpone the release.
We can implement pending tasks in backward compatible manner in aiohttp 3.2.

The release date is not scheduled yet, if you want to hop on the bus -- please hurry up (and write about your striving in a comment). I'll update blocker issues list.

**Comment by thehesiod** [comment]
no rush!  we have the work-around for now :) I'm guesstimating it will take us a couple more months to switch to aiohttp 3.x (we have a lot of services that depend in aiohttp now so things keep on getting harder to upgrade).

**Comment by asvetlov** [comment]
I've shrinked ambitious *UrlDispatcher refactoring* #2766 to just docs update #2830

**Comment by achimnol** [comment]
I'm working on #2756 to support `url_for` as well. PR coming soon!

**Comment by asvetlov** [comment]
@achimnol nice!

**Comment by asvetlov** [comment]
Done
